#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;

$container = new Container;
$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'v1.0.0');
$artisan->setName('Composer Boilerplate');

// Bind a command
$artisan->resolve(PhpUnit::class);

$artisan->run();

